### ISSUE TITLE
Creating DB via MySql creates an error

### ISSUE THREAD

**Issue by herculezs** [bewithdhanu/codeigniter-3.2.1-with-admin-LTE-Template-Intigration#4]
SQL query:

DROP DATABASE IF EXISTS `cias`
MySQL said: Documentation

"DROP DATABASE" statements are disabled.

How can I resolve it?

**Comment by bewithdhanu** [comment]
if you try it in localhost(127.0.0.1) like using xampp or wamp,DROP statements will works fine,
if you use remote mysql may you don't have such permissions to drop database
you can skip that query if you are using remote mysql,instead of that create a database with your root access to remote location or with cpanel.
